services:
  - type: web
    name: feeding-humanity
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
      - key: NPM_CONFIG_BUILD_FROM_SOURCE
        value: false 